In [1]:
import psycopg2
import requests
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
##Extracting Loation data in Nairobi Location using coordinates
from datetime import datetime

base_url = os.getenv('BASE_URL')

location_url = f"{base_url}/locations"

my_key = os.getenv('API_KEY')
header ={
   "X-API-Key": my_key 
}

params = {
    "coordinates":"-1.278560,36.821249",
    "radius":25000,
    "limit":1000
}

location_response = requests.get(url=location_url, headers=header, params=params)

In [3]:
location_response.json()

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 1000,
  'found': 16},
 'results': [{'id': 5994,
   'name': 'Nairobi CBD',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 120, 'name': 'AirNow Kenya'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 16244,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 16243,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.28156, 'longitude': 36.81883},
   'licenses': None,
   'bounds': [36.81883, -1.28156, 36.81883, -1.28156],
   'distance': 429.01874635,
   'datetimeFirst': {'utc': '2018-04-23T00:00:00Z',
    'local': '2018-04-23T03:00:00+03:00'},
   'datetimeLast': {'utc': '2018-09-13T21:00:00Z',
    'local': '2018-09-14T00:00:00+03:00'}},
  {'id': 6317,
   'name': 'Alliance Girls High',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 120, 'name': 'AirNow Kenya'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 17575,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 17576,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.26614, 'longitude': 36.66314},
   'licenses': None,
   'bounds': [36.66314, -1.26614, 36.66314, -1.26614],
   'distance': 17643.86222907,
   'datetimeFirst': {'utc': '2018-04-21T00:00:00Z',
    'local': '2018-04-21T03:00:00+03:00'},
   'datetimeLast': {'utc': '2018-11-20T23:00:00Z',
    'local': '2018-11-21T02:00:00+03:00'}},
  {'id': 352507,
   'name': 'Nairobi RR',
   'locality': 'N/A',
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 119, 'name': 'AirNow'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 2002532,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.23437, 'longitude': 36.81732},
   'licenses': [{'id': 33,
     'name': 'US Public Domain',
     'attribution': {'name': 'Unknown Governmental Organization', 'url': None},
     'dateFrom': '2016-01-30',
     'dateTo': None}],
   'bounds': [36.81732, -1.23437, 36.81732, -1.23437],
   'distance': 4898.73546723,
   'datetimeFirst': {'utc': '2022-06-16T17:00:00Z',
    'local': '2022-06-16T20:00:00+03:00'},
   'datetimeLast': {'utc': '2025-02-12T15:00:00Z',
    'local': '2025-02-12T18:00:00+03:00'}},
  {'id': 2156118,
   'name': 'Nairobi',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 9, 'name': 'Clarity'},
   'provider': {'id': 166, 'name': 'Clarity'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 4, 'name': 'Clarity Sensor'}],
   'sensors': [{'id': 7765850,
     'name': 'no2 ppb',
     'parameter': {'id': 15,
      'name': 'no2',
      'units': 'ppb',
      'displayName': 'NO₂'}},
    {'id': 7765851,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 7765852,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 7765853,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 7765854,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 7765855,
     'name': 'temperature f',
     'parameter': {'id': 128,
      'name': 'temperature',
      'units': 'f',
      'displayName': 'Temperature (F)'}}],
   'coordinates': {'latitude': -1.33159, 'longitude': 36.91271},
   'licenses': [{'id': 38,
     'name': 'CC0 1.0',
     'attribution': {'name': 'Clarity', 'url': None},
     'dateFrom': '2021-10-20',
     'dateTo': None}],
   'bounds': [36.91271, -1.33159, 36.91271, -1.33159],
   'distance': 11755.00685327,
   'datetimeFirst': {'utc': '2024-01-28T15:00:32Z',
    'local': '2024-01-28T18:00:32+03:00'},
   'datetimeLast': {'utc': '2025-10-16T05:47:28Z',
    'local': '2025-10-16T08:47:28+03:00'}},
  {'id': 2388059,
   'name': 'Nyayo Embakasi, Nairobi',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 11509, 'name': 'Unknown Person'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 7, 'name': 'Unknown AirGradient Sensor'},
    {'id': 7, 'name': 'Unknown AirGradient Sensor'}],
   'sensors': [{'id': 7970953,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 7981687,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 7981696,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 7971111,
     'name': 'pm10 µg/m³',
     'parameter': {'id': 1,
      'name': 'pm10',
      'units': 'µg/m³',
      'displayName': 'PM10'}},
    {'id': 7817013,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 7971951,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 7817012,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 7971957,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': -1.304011, 'longitude': 36.907681},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'Unknown Person', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [36.907681, -1.304011, 36.907681, -1.304011],
   'distance': 10029.46233217,
   'datetimeFirst': {'utc': '2024-02-06T05:00:00Z',
    'local': '2024-02-06T08:00:00+03:00'},
   'datetimeLast': {'utc': '2024-05-09T18:00:00Z',
    'local': '2024-05-09T21:00:00+03:00'}},
  {'id': 3394396,
   'name': 'Nairobi CMR',
   'locality': 'N/A',
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 119, 'name': 'AirNow'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 12151945,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.232511, 'longitude': 36.81732},
   'licenses': [{'id': 33,
     'name': 'US Public Domain',
     'attribution': {'name': 'Unknown Governmental Organization', 'url': None},
     'dateFrom': '2016-01-30',
     'dateTo': None}],
   'bounds': [36.81732, -1.232511, 36.81732, -1.232511],
   'distance': 5103.52601208,
   'datetimeFirst': {'utc': '2025-02-06T18:00:00Z',
    'local': '2025-02-06T21:00:00+03:00'},
   'datetimeLast': {'utc': '2025-06-26T10:00:00Z',
    'local': '2025-06-26T13:00:00+03:00'}},
  {'id': 3394397,
   'name': 'Nairobi CMR',
   'locality': 'N/A',
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 119, 'name': 'AirNow'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 12161516,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.232511, 'longitude': 36.81732},
   'licenses': [{'id': 33,
     'name': 'US Public Domain',
     'attribution': {'name': 'Unknown Governmental Organization', 'url': None},
     'dateFrom': '2016-01-30',
     'dateTo': None}],
   'bounds': [36.81732, -1.232511, 36.81732, -1.232511],
   'distance': 5103.52601208,
   'datetimeFirst': {'utc': '2025-02-10T22:00:00Z',
    'local': '2025-02-11T01:00:00+03:00'},
   'datetimeLast': {'utc': '2025-02-11T21:00:00Z',
    'local': '2025-02-12T00:00:00+03:00'}},
  {'id': 3399524,
   'name': 'Nairobi RR',
   'locality': 'N/A',
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 119, 'name': 'AirNow'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 12167724,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}}],
   'coordinates': {'latitude': -1.22291, 'longitude': 36.80549},
   'licenses': [{'id': 33,
     'name': 'US Public Domain',
     'attribution': {'name': 'Unknown Governmental Organization', 'url': None},
     'dateFrom': '2016-01-30',
     'dateTo': None}],
   'bounds': [36.80549, -1.22291, 36.80549, -1.22291],
   'distance': 6390.6778012,
   'datetimeFirst': {'utc': '2025-02-12T13:00:00Z',
    'local': '2025-02-12T16:00:00+03:00'},
   'datetimeLast': {'utc': '2025-02-17T16:00:00Z',
    'local': '2025-02-17T19:00:00+03:00'}},
  {'id': 5119477,
   'name': 'Kitisuru',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 12, 'name': 'AirGradient'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13633454,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13633455,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13633456,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13633457,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13633458,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': -1.2252518809076456,
    'longitude': 36.75807771613854},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'AirGradient', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [36.75807771613854,
    -1.2252518809076456,
    36.75807771613854,
    -1.2252518809076456],
   'distance': 9166.19005049,
   'datetimeFirst': {'utc': '2025-07-18T13:00:00Z',
    'local': '2025-07-18T16:00:00+03:00'},
   'datetimeLast': {'utc': '2025-12-09T09:00:00Z',
    'local': '2025-12-09T12:00:00+03:00'}},
  {'id': 5199863,
   'name': 'Kihumo Village || Antenna Array',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 16933, 'name': 'The Demography Project'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 24,
     'name': 'AirGradient Open Air Generation 1 (O-1PST)'}],
   'sensors': [{'id': 13691748,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 13691749,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 13691750,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 13691751,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 13691752,
     'name': 'um003 particles/cm³',
     'parameter': {'id': 125,
      'name': 'um003',
      'units': 'particles/cm³',
      'displayName': 'PM0.3 count'}}],
   'coordinates': {'latitude': -1.2618359714875163,
    'longitude': 36.686049384630266},
   'licenses': [{'id': 41,
     'name': 'CC BY 4.0',
     'attribution': {'name': 'The Demography Project', 'url': None},
     'dateFrom': '2023-07-15',
     'dateTo': None}],
   'bounds': [36.686049384630266,
    -1.2618359714875163,
    36.686049384630266,
    -1.2618359714875163],
   'distance': 15153.67032167,
   'datetimeFirst': {'utc': '2025-07-25T11:00:00Z',
    'local': '2025-07-25T14:00:00+03:00'},
   'datetimeLast': {'utc': '2026-10-17T13:00:00Z',
    'local': '2026-10-17T16:00:00+03:00'}},
  {'id': 5672958,
   'name': 'KENBIFS01',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 1, 'name': 'OpenAQ admin'},
   'provider': {'id': 12, 'name': 'Clean Air Catalyst'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 1, 'name': 'N/A'},
    {'id': 13, 'name': 'AIO 2'},
    {'id': 18, 'name': 'BAM 1022'}],
   'sensors': [{'id': 14341710,
     'name': 'bc_375 ng/m³',
     'parameter': {'id': 19861,
      'name': 'bc_375',
      'units': 'ng/m³',
      'displayName': 'BC 375nm'}},
    {'id': 14341711,
     'name': 'bc_880 ng/m³',
     'parameter': {'id': 19865,
      'name': 'bc_880',
      'units': 'ng/m³',
      'displayName': 'BC 880nm'}},
    {'id': 14038275,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 14038280,
     'name': 'pressure hpa',
     'parameter': {'id': 95,
      'name': 'pressure',
      'units': 'hpa',
      'displayName': 'Atmospheric pressure'}},
    {'id': 14038281,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 14038282,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 14341712,
     'name': 'wind_direction deg',
     'parameter': {'id': 22,
      'name': 'wind_direction',
      'units': 'deg',
      'displayName': 'Wind direction'}},
    {'id': 14341713,
     'name': 'wind_speed m/s',
     'parameter': {'id': 34,
      'name': 'wind_speed',
      'units': 'm/s',
      'displayName': 'Wind speed'}}],
   'coordinates': {'latitude': -1.2818, 'longitude': 36.8232},
   'licenses': None,
   'bounds': [36.8232, -1.2818, 36.8232, -1.2818],
   'distance': 427.42638826,
   'datetimeFirst': {'utc': '2024-09-03T14:00:00Z',
    'local': '2024-09-03T17:00:00+03:00'},
   'datetimeLast': {'utc': '2025-05-31T15:00:00Z',
    'local': '2025-05-31T18:00:00+03:00'}},
  {'id': 5672959,
   'name': 'KENBIMLK01',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 1, 'name': 'OpenAQ admin'},
   'provider': {'id': 12, 'name': 'Clean Air Catalyst'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 1, 'name': 'N/A'},
    {'id': 13, 'name': 'AIO 2'},
    {'id': 18, 'name': 'BAM 1022'}],
   'sensors': [{'id': 14341714,
     'name': 'bc_375 ng/m³',
     'parameter': {'id': 19861,
      'name': 'bc_375',
      'units': 'ng/m³',
      'displayName': 'BC 375nm'}},
    {'id': 14341715,
     'name': 'bc_470 ng/m³',
     'parameter': {'id': 19862,
      'name': 'bc_470',
      'units': 'ng/m³',
      'displayName': 'BC 470nm'}},
    {'id': 14341716,
     'name': 'bc_528 ng/m³',
     'parameter': {'id': 19863,
      'name': 'bc_528',
      'units': 'ng/m³',
      'displayName': 'BC 528nm'}},
    {'id': 14341717,
     'name': 'bc_625 ng/m³',
     'parameter': {'id': 19864,
      'name': 'bc_625',
      'units': 'ng/m³',
      'displayName': 'BC 625nm'}},
    {'id': 14341718,
     'name': 'bc_880 ng/m³',
     'parameter': {'id': 19865,
      'name': 'bc_880',
      'units': 'ng/m³',
      'displayName': 'BC 880nm'}},
    {'id': 14038279,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 14038276,
     'name': 'pressure hpa',
     'parameter': {'id': 95,
      'name': 'pressure',
      'units': 'hpa',
      'displayName': 'Atmospheric pressure'}},
    {'id': 14038277,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 14038278,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',
      'displayName': 'Temperature (C)'}},
    {'id': 14341719,
     'name': 'wind_direction deg',
     'parameter': {'id': 22,
      'name': 'wind_direction',
      'units': 'deg',
      'displayName': 'Wind direction'}},
    {'id': 14341720,
     'name': 'wind_speed m/s',
     'parameter': {'id': 34,
      'name': 'wind_speed',
      'units': 'm/s',
      'displayName': 'Wind speed'}}],
   'coordinates': {'latitude': -1.2742, 'longitude': 36.899},
   'licenses': None,
   'bounds': [36.899, -1.2742, 36.899, -1.2742],
   'distance': 8671.56709246,
   'datetimeFirst': {'utc': '2024-09-03T14:00:00Z',
    'local': '2024-09-03T17:00:00+03:00'},
   'datetimeLast': {'utc': '2025-05-31T15:00:00Z',
    'local': '2025-05-31T18:00:00+03:00'}},
  {'id': 6216058,
   'name': 'Mukuru- Pipeline',
   'locality': None,
   'timezone': 'Africa/Nairobi',
   'country': {'id': 17, 'code': 'KE', 'name': 'Kenya'},
   'owner': {'id': 12, 'name': 'AirGradient'},
   'provider': {'id': 66, 'name': 'AirGradient'},
   'isMobile': False,
   'isMonitor': False,
   'instruments': [{'id': 26,
     'name': 'AirGradient Open Air Max Generation 1 (O-M-1PPST-CE)'}],
   'sensors': [{'id': 15269707,
     'name': 'pm1 µg/m³',
     'parameter': {'id': 19,
      'name': 'pm1',
      'units': 'µg/m³',
      'displayName': 'PM1'}},
    {'id': 15269708,
     'name': 'pm25 µg/m³',
     'parameter': {'id': 2,
      'name': 'pm25',
      'units': 'µg/m³',
      'displayName': 'PM2.5'}},
    {'id': 15269709,
     'name': 'relativehumidity %',
     'parameter': {'id': 98,
      'name': 'relativehumidity',
      'units': '%',
      'displayName': 'RH'}},
    {'id': 15269710,
     'name': 'temperature c',
     'parameter': {'id': 100,
      'name': 'temperature',
      'units': 'c',

In [4]:
location_data = pd.json_normalize(location_response.json()['results'])
location_data = pd.DataFrame(location_data)
location_data

,id,name,locality,timezone,isMobile,isMonitor,instruments,sensors,licenses,bounds,...,owner.id,owner.name,provider.id,provider.name,coordinates.latitude,coordinates.longitude,datetimeFirst.utc,datetimeFirst.local,datetimeLast.utc,datetimeLast.local
0,5994,Nairobi CBD,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 16244, 'name': 'pm10 µg/m³', 'paramete...",None,"[36.81883, -1.28156, 36.81883, -1.28156]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.281560,36.818830,2018-04-23T00:00:00Z,2018-04-23T03:00:00+03:00,2018-09-13T21:00:00Z,2018-09-14T00:00:00+03:00
1,6317,Alliance Girls High,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 17575, 'name': 'pm10 µg/m³', 'paramete...",None,"[36.66314, -1.26614, 36.66314, -1.26614]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.266140,36.663140,2018-04-21T00:00:00Z,2018-04-21T03:00:00+03:00,2018-11-20T23:00:00Z,2018-11-21T02:00:00+03:00
2,352507,Nairobi RR,N/A,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 2002532, 'name': 'pm25 µg/m³', 'parame...","[{'id': 33, 'name': 'US Public Domain', 'attri...","[36.81732, -1.23437, 36.81732, -1.23437]",...,4,Unknown Governmental Organization,119,AirNow,-1.234370,36.817320,2022-06-16T17:00:00Z,2022-06-16T20:00:00+03:00,2025-02-12T15:00:00Z,2025-02-12T18:00:00+03:00
3,2156118,Nairobi,NaN,Africa/Nairobi,False,False,"[{'id': 4, 'name': 'Clarity Sensor'}]","[{'id': 7765850, 'name': 'no2 ppb', 'parameter...","[{'id': 38, 'name': 'CC0 1.0', 'attribution': ...","[36.91271, -1.33159, 36.91271, -1.33159]",...,9,Clarity,166,Clarity,-1.331590,36.912710,2024-01-28T15:00:32Z,2024-01-28T18:00:32+03:00,2025-10-16T05:47:28Z,2025-10-16T08:47:28+03:00
4,2388059,"Nyayo Embakasi, Nairobi",NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor...","[{'id': 7970953, 'name': 'pm1 µg/m³', 'paramet...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.907681, -1.304011, 36.907681, -1.304011]",...,11509,Unknown Person,66,AirGradient,-1.304011,36.907681,2024-02-06T05:00:00Z,2024-02-06T08:00:00+03:00,2024-05-09T18:00:00Z,2024-05-09T21:00:00+03:00
5,3394396,Nairobi CMR,N/A,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12151945, 'name': 'pm25 µg/m³', 'param...","[{'id': 33, 'name': 'US Public Domain', 'attri...","[36.81732, -1.232511, 36.81732, -1.232511]",...,4,Unknown Governmental Organization,119,AirNow,-1.232511,36.817320,2025-02-06T18:00:00Z,2025-02-06T21:00:00+03:00,2025-06-26T10:00:00Z,2025-06-26T13:00:00+03:00
6,3394397,Nairobi CMR,N/A,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12161516, 'name': 'pm25 µg/m³', 'param...","[{'id': 33, 'name': 'US Public Domain', 'attri...","[36.81732, -1.232511, 36.81732, -1.232511]",...,4,Unknown Governmental Organization,119,AirNow,-1.232511,36.817320,2025-02-10T22:00:00Z,2025-02-11T01:00:00+03:00,2025-02-11T21:00:00Z,2025-02-12T00:00:00+03:00
7,3399524,Nairobi RR,N/A,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","[{'id': 12167724, 'name': 'pm25 µg/m³', 'param...","[{'id': 33, 'name': 'US Public Domain', 'attri...","[36.80549, -1.22291, 36.80549, -1.22291]",...,4,Unknown Governmental Organization,119,AirNow,-1.222910,36.805490,2025-02-12T13:00:00Z,2025-02-12T16:00:00+03:00,2025-02-17T16:00:00Z,2025-02-17T19:00:00+03:00
8,5119477,Kitisuru,NaN,Africa/Nairobi,False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 13633454, 'name': 'pm1 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.75807771613854, -1.2252518809076456, 36.75...",...,12,AirGradient,66,AirGradient,-1.225252,36.758078,2025-07-18T13:00:00Z,2025-07-18T16:00:00+03:00,2025-12-09T09:00:00Z,2025-12-09T12:00:00+03:00
9,5199863,Kihumo Village || Antenna Array,NaN,Africa/Nairobi,False,False,"[{'id': 24, 'name': 'AirGradient Open Air Gene...","[{'id': 13691748, 'name': 'pm1 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.686049384630266, -1.2618359714875163, 36.6...",...,16933,The Demography Project,66,AirGradient,-1.261836,36.686049,2025-07-25T11:00:00Z,2025-07-25T14:00:00+03:00,2026-10-17T13:00:00Z,2026-10-17T16:00:00+03:00
10,5672958,KENBIFS01,NaN,Africa/Nairobi,False,True,"[{'id': 1, 'name': 'N/A'}, {'id': 13, 'name': ...","[{'id': 14341710, 'name': 'bc_375 ng/m³', 'par...",None,"[36.8232, -1.2818, 36.8232, -1.2818]",...,1,OpenAQ admin,12,Clean Air Catalyst,-1.281800,36.823200,2024-09-03T14:00:00Z,2024-09-03T17:00:00+03:00,2025-05-31T15:00:00Z,2025-05-31T18:00:00+03:00
11,5672959,KENBIMLK01,NaN,Africa/Nairobi,False,True,"[{'id': 1, 'name': 'N/A'}, {'id': 13, 'name': ...","[{'id': 14341714, 'name': 'bc_375 ng/m³', 'par...",None,"[36.899, -1.2742, 36.899, -1.2742]",...,1,OpenAQ admin,12,Clean Air Catalyst,-1.274200,36.899000,2024-09-03T14:00:00Z,2024-09-03T17:00:00+03:00,2025-05-31T15:00:00Z,2025-05-31T18:00:00+03:00
12,6216058,Mukuru- Pipeline,NaN,Africa/Nairobi,False,False,"[{'id': 26, 'name': 'AirGradient Open Air Max ...","[{'id': 15269707, 'name': 'pm1 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.8876, -1.3249, 36.8876, -1.3249]",...,12,AirGradient,66,AirGradient,-1.324900,36.887600,2026-01-26T08:00:00Z,2026-01-26T11:00:00+03:00,2026-02-06T06:00:00Z,2026-02-06T09:00:00+03:00
13,6236592,Marurui,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15420153, 'name': 'pm1 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.87397, -1.20912, 36.87397, -1.20912]",...,12,AirGradient,66,AirGradient,-1.209120,36.873970,2026-02-11T15:00:00Z,2026-02-11T18:00:00+03:00,2026-02-23T17:00:00Z,2026-02-23T20:00:00+03:00
14,6237507,Providence Academy,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","[{'id': 15427114, 'name': 'pm1 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.881388, -1.230255, 36.881388, -1.230255]",...,12,AirGradient,66,AirGradient,-1.230255,36.881388,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-06-16T07:00:00Z,2026-06-16T10:00:00+03:00
15,6326576,"Nairobi, University of Nairobi, Parklands Camp...",NaN,Africa/Nairobi,False,True,"[{'id': 18, 'name': 'BAM 1022'}]","[{'id': 16091678, 'name': 'pm25 µg/m³', 'param...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.818, -1.26, 36.818, -1.26]",...,23894,GEOHealth Hub for Eastern Africa,441,GeoHealth,-1.260000,36.818000,2019-08-20T21:00:00Z,2019-08-21T00:00:00+03:00,2023-02-28T20:00:00Z,2023-02-28T23:00:00+03:00

In [5]:
## Exploding data is normalizing a column within a normalized dataframe
exploded_location_data = location_data.explode(column='sensors')
exploded_location_data

,id,name,locality,timezone,isMobile,isMonitor,instruments,sensors,licenses,bounds,...,owner.id,owner.name,provider.id,provider.name,coordinates.latitude,coordinates.longitude,datetimeFirst.utc,datetimeFirst.local,datetimeLast.utc,datetimeLast.local
0,5994,Nairobi CBD,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","{'id': 16244, 'name': 'pm10 µg/m³', 'parameter...",None,"[36.81883, -1.28156, 36.81883, -1.28156]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.281560,36.818830,2018-04-23T00:00:00Z,2018-04-23T03:00:00+03:00,2018-09-13T21:00:00Z,2018-09-14T00:00:00+03:00
0,5994,Nairobi CBD,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","{'id': 16243, 'name': 'pm25 µg/m³', 'parameter...",None,"[36.81883, -1.28156, 36.81883, -1.28156]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.281560,36.818830,2018-04-23T00:00:00Z,2018-04-23T03:00:00+03:00,2018-09-13T21:00:00Z,2018-09-14T00:00:00+03:00
1,6317,Alliance Girls High,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","{'id': 17575, 'name': 'pm10 µg/m³', 'parameter...",None,"[36.66314, -1.26614, 36.66314, -1.26614]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.266140,36.663140,2018-04-21T00:00:00Z,2018-04-21T03:00:00+03:00,2018-11-20T23:00:00Z,2018-11-21T02:00:00+03:00
1,6317,Alliance Girls High,NaN,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","{'id': 17576, 'name': 'pm25 µg/m³', 'parameter...",None,"[36.66314, -1.26614, 36.66314, -1.26614]",...,4,Unknown Governmental Organization,120,AirNow Kenya,-1.266140,36.663140,2018-04-21T00:00:00Z,2018-04-21T03:00:00+03:00,2018-11-20T23:00:00Z,2018-11-21T02:00:00+03:00
2,352507,Nairobi RR,N/A,Africa/Nairobi,False,True,"[{'id': 2, 'name': 'Government Monitor'}]","{'id': 2002532, 'name': 'pm25 µg/m³', 'paramet...","[{'id': 33, 'name': 'US Public Domain', 'attri...","[36.81732, -1.23437, 36.81732, -1.23437]",...,4,Unknown Governmental Organization,119,AirNow,-1.234370,36.817320,2022-06-16T17:00:00Z,2022-06-16T20:00:00+03:00,2025-02-12T15:00:00Z,2025-02-12T18:00:00+03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,6237507,Providence Academy,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","{'id': 15427115, 'name': 'pm25 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.881388, -1.230255, 36.881388, -1.230255]",...,12,AirGradient,66,AirGradient,-1.230255,36.881388,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-06-16T07:00:00Z,2026-06-16T10:00:00+03:00
14,6237507,Providence Academy,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","{'id': 15427116, 'name': 'relativehumidity %',...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.881388, -1.230255, 36.881388, -1.230255]",...,12,AirGradient,66,AirGradient,-1.230255,36.881388,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-06-16T07:00:00Z,2026-06-16T10:00:00+03:00
14,6237507,Providence Academy,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","{'id': 15427117, 'name': 'temperature c', 'par...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.881388, -1.230255, 36.881388, -1.230255]",...,12,AirGradient,66,AirGradient,-1.230255,36.881388,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-06-16T07:00:00Z,2026-06-16T10:00:00+03:00
14,6237507,Providence Academy,NaN,Africa/Nairobi,False,False,"[{'id': 7, 'name': 'Unknown AirGradient Sensor'}]","{'id': 15427118, 'name': 'um003 particles/cm³'...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.881388, -1.230255, 36.881388, -1.230255]",...,12,AirGradient,66,AirGradient,-1.230255,36.881388,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-06-16T07:00:00Z,2026-06-16T10:00:00+03:00
15,6326576,"Nairobi, University of Nairobi, Parklands Camp...",NaN,Africa/Nairobi,False,True,"[{'id': 18, 'name': 'BAM 1022'}]","{'id': 16091678, 'name': 'pm25 µg/m³', 'parame...","[{'id': 41, 'name': 'CC BY 4.0', 'attribution'...","[36.818, -1.26, 36.818, -1.26]",...,23894,GEOHealth Hub for Eastern Africa,441,GeoHealth,-1.260000,36.818000,2019-08-20T21:00:00Z,2019-08-21T00:00:00+03:00,2023-02-28T20:00:00Z,2023-02-28T23:00:00+03:00

In [6]:
normalized_location_data =pd.json_normalize(exploded_location_data['sensors']).add_prefix('sensor.')
final_location_data = exploded_location_data.drop(columns=['sensors']).join(normalized_location_data)
final_location_data.columns

Index(['id', 'name', 'locality', 'timezone', 'isMobile', 'isMonitor',
       'instruments', 'licenses', 'bounds', 'distance', 'country.id',
       'country.code', 'country.name', 'owner.id', 'owner.name', 'provider.id',
       'provider.name', 'coordinates.latitude', 'coordinates.longitude',
       'datetimeFirst.utc', 'datetimeFirst.local', 'datetimeLast.utc',
       'datetimeLast.local', 'sensor.id', 'sensor.name', 'sensor.parameter.id',
       'sensor.parameter.name', 'sensor.parameter.units',
       'sensor.parameter.displayName'],
      dtype='str')

In [7]:
sensor_location_data = final_location_data[['id', 'name','sensor.id', 'sensor.parameter.name', 'sensor.parameter.units','coordinates.latitude', 'coordinates.longitude']]
sensor_location_data

,id,name,sensor.id,sensor.parameter.name,sensor.parameter.units,coordinates.latitude,coordinates.longitude
0,5994,Nairobi CBD,16244,pm10,µg/m³,-1.281560,36.818830
0,5994,Nairobi CBD,16243,pm25,µg/m³,-1.281560,36.818830
0,5994,Nairobi CBD,16244,pm10,µg/m³,-1.281560,36.818830
0,5994,Nairobi CBD,16243,pm25,µg/m³,-1.281560,36.818830
1,6317,Alliance Girls High,17575,pm10,µg/m³,-1.266140,36.663140
...,...,...,...,...,...,...,...
14,6237507,Providence Academy,15427115,pm25,µg/m³,-1.230255,36.881388
14,6237507,Providence Academy,15427116,relativehumidity,%,-1.230255,36.881388
14,6237507,Providence Academy,15427117,temperature,c,-1.230255,36.881388
14,6237507,Providence Academy,15427118,um003,particles/cm³,-1.230255,36.881388
15,6326576,"Nairobi, University of Nairobi, Parklands Camp...",16091678,pm25,µg/m³,-1.260000,36.818000

The above data has the follwoing columns necessary in making of the final table

1. location_id
2. location_name
3. Sensor_id
4. sensor.Paramater.name
5. sensor.Parameter.units

Measurement, value and time stamp will be gotten from  measurement

In [8]:
##Extracting hourly measurements
from datetime import datetime, timedelta

yesterday = datetime.now() - timedelta(days=1)
date_from = datetime(yesterday.year, yesterday.month, yesterday.day, 0,0,0)
date_to = datetime(yesterday.year, yesterday.month, yesterday.day, 23, 59,59)
param = {
    "datetime_from":date_from.isoformat(),
    "datetime_to": date_to.isoformat(),
    "limit":1000,
    "page":1
}

measurement_data = []

measurements_url = f"{base_url}/sensors/{15427116}/hours"
measurement_response = requests.get(measurements_url, headers= header)


"""
for sensor_id in final_location_data['sensor.id']:
    measurements_url = f"{base_url}/sensors/{36.881388}/hours"
    measurement_response = requests.get(measurements_url, headers= header)
    measurement_data.append(measurement_response.json()['results'])"""

measurement_response.json()

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': '>100'},
 'results': [{'value': 30.4,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T12:00:00Z',
     'local': '2026-02-12T15:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T13:00:00Z',
     'local': '2026-02-12T16:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 30.403958384195963,
    'q02': 30.403958384195963,
    'q25': 30.403958384195963,
    'median': 30.403958384195963,
    'q75': 30.403958384195963,
    'q98': 30.403958384195963,
    'max': 30.403958384195963,
    'avg': 30.403958384195963,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T12:00:00Z',
     'local': '2026-02-12T15:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T13:00:00Z',
     'local': '2026-02-12T16:00:00+03:00'}}},
  {'value': 24.0,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T13:00:00Z',
     'local': '2026-02-12T16:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T14:00:00Z',
     'local': '2026-02-12T17:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 23.993833255767825,
    'q02': 23.993833255767825,
    'q25': 23.993833255767825,
    'median': 23.993833255767825,
    'q75': 23.993833255767825,
    'q98': 23.993833255767825,
    'max': 23.993833255767825,
    'avg': 23.993833255767825,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T13:00:00Z',
     'local': '2026-02-12T16:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T14:00:00Z',
     'local': '2026-02-12T17:00:00+03:00'}}},
  {'value': 23.2,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T14:00:00Z',
     'local': '2026-02-12T17:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T15:00:00Z',
     'local': '2026-02-12T18:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 23.23954161008199,
    'q02': 23.23954161008199,
    'q25': 23.23954161008199,
    'median': 23.23954161008199,
    'q75': 23.23954161008199,
    'q98': 23.23954161008199,
    'max': 23.23954161008199,
    'avg': 23.23954161008199,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T14:00:00Z',
     'local': '2026-02-12T17:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T15:00:00Z',
     'local': '2026-02-12T18:00:00+03:00'}}},
  {'value': 23.9,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T15:00:00Z',
     'local': '2026-02-12T18:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T16:00:00Z',
     'local': '2026-02-12T19:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 23.928166675567624,
    'q02': 23.928166675567624,
    'q25': 23.928166675567624,
    'median': 23.928166675567624,
    'q75': 23.928166675567624,
    'q98': 23.928166675567624,
    'max': 23.928166675567624,
    'avg': 23.928166675567624,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T15:00:00Z',
     'local': '2026-02-12T18:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T16:00:00Z',
     'local': '2026-02-12T19:00:00+03:00'}}},
  {'value': 25.4,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T16:00:00Z',
     'local': '2026-02-12T19:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T17:00:00Z',
     'local': '2026-02-12T20:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 25.418666617075598,
    'q02': 25.418666617075598,
    'q25': 25.418666617075598,
    'median': 25.418666617075598,
    'q75': 25.418666617075598,
    'q98': 25.418666617075598,
    'max': 25.418666617075598,
    'avg': 25.418666617075598,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T16:00:00Z',
     'local': '2026-02-12T19:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T17:00:00Z',
     'local': '2026-02-12T20:00:00+03:00'}}},
  {'value': 26.2,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T17:00:00Z',
     'local': '2026-02-12T20:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T18:00:00Z',
     'local': '2026-02-12T21:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 26.202833461761475,
    'q02': 26.202833461761475,
    'q25': 26.202833461761475,
    'median': 26.202833461761475,
    'q75': 26.202833461761475,
    'q98': 26.202833461761475,
    'max': 26.202833461761475,
    'avg': 26.202833461761475,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T17:00:00Z',
     'local': '2026-02-12T20:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T18:00:00Z',
     'local': '2026-02-12T21:00:00+03:00'}}},
  {'value': 27.0,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T18:00:00Z',
     'local': '2026-02-12T21:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T19:00:00Z',
     'local': '2026-02-12T22:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 27.011499977111814,
    'q02': 27.011499977111814,
    'q25': 27.011499977111814,
    'median': 27.011499977111814,
    'q75': 27.011499977111814,
    'q98': 27.011499977111814,
    'max': 27.011499977111814,
    'avg': 27.011499977111814,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T18:00:00Z',
     'local': '2026-02-12T21:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T19:00:00Z',
     'local': '2026-02-12T22:00:00+03:00'}}},
  {'value': 28.0,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T19:00:00Z',
     'local': '2026-02-12T22:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T20:00:00Z',
     'local': '2026-02-12T23:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 28.02933320999145,
    'q02': 28.02933320999145,
    'q25': 28.02933320999145,
    'median': 28.02933320999145,
    'q75': 28.02933320999145,
    'q98': 28.02933320999145,
    'max': 28.02933320999145,
    'avg': 28.02933320999145,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T19:00:00Z',
     'local': '2026-02-12T22:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T20:00:00Z',
     'local': '2026-02-12T23:00:00+03:00'}}},
  {'value': 29.1,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T20:00:00Z',
     'local': '2026-02-12T23:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T21:00:00Z',
     'local': '2026-02-13T00:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 29.088333288828526,
    'q02': 29.088333288828526,
    'q25': 29.088333288828526,
    'median': 29.088333288828526,
    'q75': 29.088333288828526,
    'q98': 29.088333288828526,
    'max': 29.088333288828526,
    'avg': 29.088333288828526,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T20:00:00Z',
     'local': '2026-02-12T23:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T21:00:00Z',
     'local': '2026-02-13T00:00:00+03:00'}}},
  {'value': 29.9,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T21:00:00Z',
     'local': '2026-02-13T00:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T22:00:00Z',
     'local': '2026-02-13T01:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 29.918999926249185,
    'q02': 29.918999926249185,
    'q25': 29.918999926249185,
    'median': 29.918999926249185,
    'q75': 29.918999926249185,
    'q98': 29.918999926249185,
    'max': 29.918999926249185,
    'avg': 29.918999926249185,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T21:00:00Z',
     'local': '2026-02-13T00:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T22:00:00Z',
     'local': '2026-02-13T01:00:00+03:00'}}},
  {'value': 30.6,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T22:00:00Z',
     'local': '2026-02-13T01:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T23:00:00Z',
     'local': '2026-02-13T02:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 30.568666744232175,
    'q02': 30.568666744232175,
    'q25': 30.568666744232175,
    'median': 30.568666744232175,
    'q75': 30.568666744232175,
    'q98': 30.568666744232175,
    'max': 30.568666744232175,
    'avg': 30.568666744232175,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T22:00:00Z',
     'local': '2026-02-13T01:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-12T23:00:00Z',
     'local': '2026-02-13T02:00:00+03:00'}}},
  {'value': 31.1,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-12T23:00:00Z',
     'local': '2026-02-13T02:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T00:00:00Z',
     'local': '2026-02-13T03:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 31.14438895119561,
    'q02': 31.14438895119561,
    'q25': 31.14438895119561,
    'median': 31.14438895119561,
    'q75': 31.14438895119561,
    'q98': 31.14438895119561,
    'max': 31.14438895119561,
    'avg': 31.14438895119561,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-12T23:00:00Z',
     'local': '2026-02-13T02:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T00:00:00Z',
     'local': '2026-02-13T03:00:00+03:00'}}},
  {'value': 31.6,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T00:00:00Z',
     'local': '2026-02-13T03:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T01:00:00Z',
     'local': '2026-02-13T04:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 31.5773333867391,
    'q02': 31.5773333867391,
    'q25': 31.5773333867391,
    'median': 31.5773333867391,
    'q75': 31.5773333867391,
    'q98': 31.5773333867391,
    'max': 31.5773333867391,
    'avg': 31.5773333867391,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T00:00:00Z',
     'local': '2026-02-13T03:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T01:00:00Z',
     'local': '2026-02-13T04:00:00+03:00'}}},
  {'value': 32.0,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T01:00:00Z',
     'local': '2026-02-13T04:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T02:00:00Z',
     'local': '2026-02-13T05:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 31.967999903361,
    'q02': 31.967999903361,
    'q25': 31.967999903361,
    'median': 31.967999903361,
    'q75': 31.967999903361,
    'q98': 31.967999903361,
    'max': 31.967999903361,
    'avg': 31.967999903361,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T01:00:00Z',
     'local': '2026-02-13T04:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T02:00:00Z',
     'local': '2026-02-13T05:00:00+03:00'}}},
  {'value': 32.1,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T02:00:00Z',
     'local': '2026-02-13T05:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T03:00:00Z',
     'local': '2026-02-13T06:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 32.091666825612386,
    'q02': 32.091666825612386,
    'q25': 32.091666825612386,
    'median': 32.091666825612386,
    'q75': 32.091666825612386,
    'q98': 32.091666825612386,
    'max': 32.091666825612386,
    'avg': 32.091666825612386,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T02:00:00Z',
     'local': '2026-02-13T05:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T03:00:00Z',
     'local': '2026-02-13T06:00:00+03:00'}}},
  {'value': 32.4,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T03:00:00Z',
     'local': '2026-02-13T06:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T04:00:00Z',
     'local': '2026-02-13T07:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 32.39999987284343,
    'q02': 32.39999987284343,
    'q25': 32.39999987284343,
    'median': 32.39999987284343,
    'q75': 32.39999987284343,
    'q98': 32.39999987284343,
    'max': 32.39999987284343,
    'avg': 32.39999987284343,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T03:00:00Z',
     'local': '2026-02-13T06:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T04:00:00Z',
     'local': '2026-02-13T07:00:00+03:00'}}},
  {'value': 31.8,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T04:00:00Z',
     'local': '2026-02-13T07:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T05:00:00Z',
     'local': '2026-02-13T08:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 31.8236665725708,
    'q02': 31.8236665725708,
    'q25': 31.8236665725708,
    'median': 31.8236665725708,
    'q75': 31.8236665725708,
    'q98': 31.8236665725708,
    'max': 31.8236665725708,
    'avg': 31.8236665725708,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T04:00:00Z',
     'local': '2026-02-13T07:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T05:00:00Z',
     'local': '2026-02-13T08:00:00+03:00'}}},
  {'value': 31.8,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T05:00:00Z',
     'local': '2026-02-13T08:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T06:00:00Z',
     'local': '2026-02-13T09:00:00+03:00'}},
   'coordinates': None,
   'summary': {'min': 31.75999994277954,
    'q02': 31.75999994277954,
    'q25': 31.75999994277954,
    'median': 31.75999994277954,
    'q75': 31.75999994277954,
    'q98': 31.75999994277954,
    'max': 31.75999994277954,
    'avg': 31.75999994277954,
    'sd': None},
   'coverage': {'expectedCount': 1,
    'expectedInterval': '01:00:00',
    'observedCount': 1,
    'observedInterval': '01:00:00',
    'percentComplete': 100.0,
    'percentCoverage': 100.0,
    'datetimeFrom': {'utc': '2026-02-13T05:00:00Z',
     'local': '2026-02-13T08:00:00+03:00'},
    'datetimeTo': {'utc': '2026-02-13T06:00:00Z',
     'local': '2026-02-13T09:00:00+03:00'}}},
  {'value': 31.4,
   'flagInfo': {'hasFlags': False},
   'parameter': {'id': 98,
    'name': 'relativehumidity',
    'units': '%',
    'displayName': None},
   'period': {'label': '1hour',
    'interval': '01:00:00',
    'datetimeFrom': {'utc': '2026-02-13T06:00:00Z',

In [9]:
#measurement_data = measurement_data[0]
flat_measurement_data = pd.json_normalize(measurement_response.json()['results'])
flat_measurement_data

,value,coordinates,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,period.label,period.interval,period.datetimeFrom.utc,...,coverage.expectedCount,coverage.expectedInterval,coverage.observedCount,coverage.observedInterval,coverage.percentComplete,coverage.percentCoverage,coverage.datetimeFrom.utc,coverage.datetimeFrom.local,coverage.datetimeTo.utc,coverage.datetimeTo.local
0,30.4,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-12T12:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-12T12:00:00Z,2026-02-12T15:00:00+03:00,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00
1,24.0,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-12T13:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-12T13:00:00Z,2026-02-12T16:00:00+03:00,2026-02-12T14:00:00Z,2026-02-12T17:00:00+03:00
2,23.2,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-12T14:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-12T14:00:00Z,2026-02-12T17:00:00+03:00,2026-02-12T15:00:00Z,2026-02-12T18:00:00+03:00
3,23.9,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-12T15:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-12T15:00:00Z,2026-02-12T18:00:00+03:00,2026-02-12T16:00:00Z,2026-02-12T19:00:00+03:00
4,25.4,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-12T16:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-12T16:00:00Z,2026-02-12T19:00:00+03:00,2026-02-12T17:00:00Z,2026-02-12T20:00:00+03:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,43.3,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-17T04:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-17T04:00:00Z,2026-02-17T07:00:00+03:00,2026-02-17T05:00:00Z,2026-02-17T08:00:00+03:00
96,40.6,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-17T05:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-17T05:00:00Z,2026-02-17T08:00:00+03:00,2026-02-17T06:00:00Z,2026-02-17T09:00:00+03:00
97,43.4,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-17T06:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-17T06:00:00Z,2026-02-17T09:00:00+03:00,2026-02-17T07:00:00Z,2026-02-17T10:00:00+03:00
98,38.8,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-17T07:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-17T07:00:00Z,2026-02-17T10:00:00+03:00,2026-02-17T08:00:00Z,2026-02-17T11:00:00+03:00
99,42.4,None,False,98,relativehumidity,%,None,1hour,01:00:00,2026-02-18T11:00:00Z,...,1,01:00:00,1,01:00:00,100.0,100.0,2026-02-18T11:00:00Z,2026-02-18T14:00:00+03:00,2026-02-18T12:00:00Z,2026-02-18T15:00:00+03:00

### Here are the values our table is required to have

Location Id

Location Name

Sensor_id - sensors

Parameter_name - Measurement data

Parameter Units - Measurement data

Value - Measurement data

Measurement timestamp

Loaded timestamp - Generated upon running

In [10]:
location_data.columns

Index(['id', 'name', 'locality', 'timezone', 'isMobile', 'isMonitor',
       'instruments', 'sensors', 'licenses', 'bounds', 'distance',
       'country.id', 'country.code', 'country.name', 'owner.id', 'owner.name',
       'provider.id', 'provider.name', 'coordinates.latitude',
       'coordinates.longitude', 'datetimeFirst.utc', 'datetimeFirst.local',
       'datetimeLast.utc', 'datetimeLast.local'],
      dtype='str')

In [11]:
location_data['sensors'][0][1]['id']

16243

In [12]:
location_data['sensors'][0][0]['id']

16244

In [13]:
final_sensor_measurement_data = [flat_measurement_data['value'], flat_measurement_data['period.datetimeFrom.utc'],]